# Generated by Django 5.1.2 on 2024-11-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_superuser',
        ),
    ]
