# Generated by Django 5.1.2 on 2024-11-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_paciente_grau_parentesco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('casado', 'Casado'), ('solteiro', 'Solteiro'), ('divorciado', 'Divorciado'), ('viuvo', 'Viuvo'), ('uniao estavel', 'Uniao Estavel')], max_length=50, null=True),
        ),
    ]
