# Generated by Django 5.1.2 on 2024-11-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='encaminhamentos',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='exames_solicitados',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='medicamentos_prescritos',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='tratamento_recomendado',
        ),
        migrations.AddField(
            model_name='prontuario',
            name='horario',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prontuario',
            name='medicamento_aplicado',
            field=models.CharField(choices=[('Selecione uma opção', 'Selecione uma opção'), ('Paracetamol', 'Paracetamol'), ('Ibuprofeno', 'Ibuprofeno'), ('Dipirona', 'Dipirona'), ('AAS', 'AAS'), ('Amoxicilina', 'Amoxicilina'), ('Omeprazol', 'Omeprazol'), ('Metformina', 'Metformina'), ('Insulina', 'Insulina'), ('Losartana', 'Losartana'), ('Clonazepam', 'Clonazepam'), ('Diazepam', 'Diazepam'), ('Captopril', 'Captopril'), ('Enalapril', 'Enalapril'), ('Simeticona', 'Simeticona'), ('Diclofenaco', 'Diclofenaco')], default='Selecione uma opção', max_length=100),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='pressao_arterial',
            field=models.CharField(choices=[('Selecione uma opção', 'Selecione uma opção'), ('120/80', '120/80 mmHg (Normal)'), ('130/85', '130/85 mmHg (Normal Alta)'), ('140/90', '140/90 mmHg (Hipertensão Grau 1)'), ('160/100', '160/100 mmHg (Hipertensão Grau 2)'), ('180/110', '180/110 mmHg (Hipertensão Grau 3)'), ('<90/<60', 'Menor que 90/60 mmHg (Hipotensão)')], default='Selecione uma opção', max_length=20),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='temperatura',
            field=models.CharField(choices=[('Selecione uma opção', 'Selecione uma opção'), ('36.0', '36.0 °C (Normal)'), ('37.0', '37.0 °C (Febril Leve)'), ('38.0', '38.0 °C (Febre)'), ('39.0', '39.0 °C (Febre Alta)'), ('40.0', '40.0 °C (Hipertermia Grave)'), ('<35.0', '<35.0 °C (Hipotermia)')], default='Selecione uma opção', max_length=20),
        ),
    ]
