# Generated by Django 5.1.2 on 2024-11-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_prontuario_diagnostico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='medicamento_aplicado',
        ),
        migrations.AddField(
            model_name='prontuario',
            name='medicamentos_aplicados',
            field=models.TextField(blank=True, null=True),
        ),
    ]
