# Generated by Django 5.1.2 on 2024-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_paciente_medicamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='doencas_cronicas',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
