# Generated by Django 5.1.2 on 2024-11-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_paciente_doencas_cronicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='frequencia_cardiaca',
            field=models.CharField(choices=[('Selecione uma opção', 'Selecione uma opção'), ('60-100', '60-100 bpm (Normal)'), ('<60', 'Menor que 60 bpm (Bradicardia)'), ('>100', 'Maior que 100 bpm (Taquicardia)')], default='Selecione uma opção', max_length=50),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='frequencia_respiratoria',
            field=models.CharField(choices=[('Selecione uma opção', 'Selecione uma opção'), ('12-20', '12-20 rpm (Normal)'), ('<12', 'Menor que 12 rpm (Bradipneia)'), ('>20', 'Maior que 20 rpm (Taquipneia)')], default='Selecione uma opção', max_length=50),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='glicemia',
            field=models.CharField(choices=[('Selecione uma opção', 'Selecione uma opção'), ('70-99', '70-99 mg/dL (Normal)'), ('100-125', '100-125 mg/dL (Pré-diabetes)'), ('>126', 'Maior que 126 mg/dL (Diabetes)'), ('<70', 'Menor que 70 mg/dL (Hipoglicemia)')], default='Selecione uma opção', max_length=50),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='saturacao_oxigenio',
            field=models.CharField(choices=[('Selecione uma opção', 'Selecione uma opção'), ('95-100', '95-100% (Normal)'), ('90-94', '90-94% (Leve Hipóxia)'), ('<90', 'Menor que 90% (Hipóxia Grave)')], default='Selecione uma opção', max_length=50),
        ),
    ]
